name: CI

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: pnpm/action-setup@v5.0.0
      - uses: actions/setup-node@v6.3.0
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm -r run build
      - run: pnpm -r run lint
      - run: pnpm -r run test
