name: Deploy Next Website

on:
  push:
    branches:
      - next

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Install and Build
        run: |
          pnpm install
          pnpm -r run build
        env:
          WEBSITE_BASE_PATH: '/react-naver-maps/next'

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: website/out
          target-folder: './next'
          clean: false
