name: Deploy Website

on:
  push:
    branches:
      - main

env:
  NEXT_PUBLIC_GA_TRACKING_ID: G-51RCXPWJLZ
  NEXT_PUBLIC_WEBSITE_BASE_PATH: '/react-naver-maps'

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Install and Build
        run: |
          pnpm install
          pnpm -r run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: website/out
          clean: false
